---
{{ if .Values.authService.ingress.enable }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    run: auth-service
  annotations:
    {{ if (.Values.authService.ingress.class) }}
    kubernetes.io/ingress.class: {{ .Values.authService.ingress.class }}
    {{ end }}
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  name: auth-service
  namespace: {{ .Release.Namespace }}
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: auth-service
                port:
                  number: 5000
            path: /
            pathType: Prefix
      {{ if (.Values.authService.ingress.host) }}
      host: {{ .Values.authService.ingress.host }}
      {{ end }}
  tls:
    {{ if (.Values.authService.ingress.host) }}
    - hosts:
      - {{ .Values.authService.ingress.host }}
    {{ else }}
    - hosts: []
    {{ end }}
{{ end }}
